# Greeter: Greeter.c
# 	gcc -ansi -static -fno-stack-protector -z execstack -g -no-pie -m32 Greeter.c -o Greeter

Shellcode: Shellcode.c
	gcc -z execstack -m32 Shellcode.c -o Shellcode

clean:
	# rm Greeter
	rm Shellcode
